import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeaderPage from "../components/HomePage";
import HomePage from "../components/HomePage";
import Layout from "../components/Layout";

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <iframe
          src="https://us4.list-manage.com/contact-form?u=a45ca27fcc08e4bed1fc56b51&form_id=5281af0ccb5217b698e205555387815a"
          title="Contact us"
          height="800"
        ></iframe>
      </Layout>
    </div>
  );
}
