import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeaderPage from "../components/HomePage";
import HomePage from "../components/HomePage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nftphile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://cdn.splitbee.io/sb.js"></script>
      </Head>

      <HomePage />
    </div>
  );
}
